version: '3'
services:
        web:
                image: striverr
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8503:8503"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
